---
- op: replace
  path: /spec/template/spec/containers/0/name
  value: base-postgres
- op: add
  path: /spec/template/spec/containers/0/ports
  value:
    - name: http
      containerPort: 5432
- op: add
  path: /spec/template/spec/containers/0/imagePullPolicy
  value: "Never"
- op: add
  path: /spec/template/spec/volumes
  value: 
    - name: postgresdb
      persistentVolumeClaim:
        claimName: base-volume-claim-postgres
- op: add
  path: /spec/template/spec/containers/0/envFrom
  value:
    - configMapRef:
        name: config-map--postgres
- op: add
  path: /spec/template/spec/containers/0/volumeMounts
  value:
    - mountPath: /var/lib/postgresql/data
      name: postgresdb