---
- op: replace
  path: /spec/template/spec/containers/0/name
  value: base-postgres
- op: add
  path: /spec/template/spec/containers/0/ports
  value:
    - name: http
      containerPort: 5432
- op: add
  path: /spec/template/spec/containers/0/imagePullPolicy
  value: "IfNotPresent"