apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# The common label used for labels and Selectors.
commonLabels:
  app.kubernetes.io/name: base-postgres

patches:
- path: ./patch/deployment.yaml
  target:
    kind: Deployment
    name: base
- path: ./patch/service.yaml
  target:
    kind: Service
    name: base