# define a resource for volume chain
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  # Name the volume chain
  name: base-claim
  labels:
    app: base-claim
spec:
  storageClassName: manual
  accessModes:
    # Allow ReadWrite to multiple pods
    - ReadWriteMany
  # PVC requesting resources
  resources:
    requests:
      # the PVC storage
      storage: 8Gi