apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app-idp
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: idp
    name: in-cluster
  project: root-project-idp
  source:
    path: app/idp/app-bundle
    repoURL: https://github.com/jdellostritto/k8s-platform-musical-waffle
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true