apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- path: ./patch/persistentVolume.yaml
  target:
    kind: PersistentVolume
    name: base-volume
- path: ./patch/persistentVolumeClaim.yaml
  target:
    kind: PersistentVolumeClaim
    name: base-volume-claim