apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-appbundle-cell-1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cell1
    name: in-cluster
  project: project-cell-1
  source:
    path: apps/app-bundle/cell-1
    repoURL: https://github.com/jdellostritto/k8s-platform-musical-waffle
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true